### ISSUE TITLE
Framework or library?

### ISSUE THREAD

**Issue by danse** [passy/ltxbot#24]
Hello, i'm starting to write a Twitter bot and i am looking at this as a working example. I assume that there is an amount of boilerplate that is repeated for almost any bot, so we might start a framework or a library of common functions. I looked for this package on Hackage but i couldn't find it. I think that if the library here was published on Hackage, we would have a very low threshold for collecting reusable logic. What do you think?

**Comment by passy** [comment]
I don't think there's too much boilerplate you need to repeat. Unless you want to write a bot that's *very* similar to this one, i.e. listen for mentions and reply with an image. :)

They way the code is currently structured does not lend itself very well to publishing as the entire "library" of this built with the intention of being used by the main app.

All of that said, if you want to extract some pieces that you think are useful and publish them as stand-alone library, please go ahead! I'd be happy to base this on top of it whenever it's ready. :)

**Comment by danse** [comment]
Right, i realised eventually that the code is not very long. In order to extract a meaningful library i guess that we would want to have more use cases, and a bigger chunk of logic to reuse. I'll go ahead just with copying for now, i'll get in touch (and maybe reopen the issue) if i'll spot something worth encapsulating. Cheers
